GET http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdW1hdSIsImlkIjoiNjM2NGNiYzg3MjEyOWRiOGE5MTNhNzNlIiwiaWF0IjoxNjY4Nzc0MjIxfQ.O_DB_p4X67DcfiKAwAY-DXLW1naTjXjGCHxBpPFKB5A
###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdW1hdSIsImlkIjoiNjM3Nzg5YmQyOTlhN2UzZWRkMTBmYTI2IiwiaWF0IjoxNjY4Nzc4NDg2fQ.SqGS1W2IztdAaYoqksTiR3LVzrzbsIyn_70H_HFLtkE

{
    "title": "Novo 4",
    "author": "Mauricio Nascimento",
    "url": "www.novo.com",
    "likes": 9
}

###

POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "maumau",
    "name": "Mauricio",
    "password": "teste123"
}

###
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "username":"maumau",
    "password":"teste123"
}

###
DELETE http://localhost:3003/api/blogs/637788c22f3278f9ddcb8b51 HTTP/1.1
