GET http://localhost:3003/api/blog

###

POST http://localhost:3003/api/blog HTTP/1.1
Content-Type: application/json

{
    "title": "Segundo Flamerda",
    "author": "Mauricio Nascimento",
    "url": "www.vaitomarnocuflamengo.com",
    "likes": 5
}