POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MzVhZGE5MGZiNTg2YjJlMjE0OWVmNmUiLCJpYXQiOjE2NjcyMjQ0NjR9.Q4ERzVxwOfOgAbaJnFXwRMSw9fChfyQ0iBmH-ZBzpvw

{
    "content": "Single page apps use token to validade",
    "important": true
}

###

GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/633c49792d8614626095c18a

###

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkaien",
    "password": "salainen"
}

###
POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "username":"mluukkai",
    "password":"salainen"
}

###

GET http://localhost:3001/api/users